### ISSUE TITLE
Openvas Support

### ISSUE THREAD

**Issue by OscarArgueyo** [stevecoward/nasl-parser#8]
Is it possible that only work with Nessus and not with OpenVas files.

When I run with my openvas nasl files, the parser get all the variables empty. 

{'attributes': {},
 'bugtraq_id': [11071],
 'category': 'ACT_GATHER_INFO',
 'checks': [],
 'copyright': [],
 'cve_id': [],
 'cvs_date': '',
 'cvss3_base_vector': '',
 'cvss3_temporal_vector': '',
 'cvss_base_vector': '',
 'cvss_temporal_vector': '',
 'cwe_id': [],
 'family': [],
 'id': 0,
 'name': [],
 'osvdb_id': [],
 'summary': '',
 'version': '',
 'xref': {}}

**Comment by stevecoward** [comment]
Hi,

Feel free to fork and work on something that will also work with OpenVAS. My priorities have shifted and this project hasn't been updated in a while.
